// Generated by tools/character/dev.py; edit the JSON fixture, not this file.
#pragma once

typedef struct { const char *name; const char *detail; } character_pack_entry_t;
#define CHARACTER_PACK_ID "synthetic-mara-vale"
#define CHARACTER_PACK_GENERATION 0x85352F15u
#define CHARACTER_PACK_NAME "Mara Vale"
#define CHARACTER_PACK_ANCESTRY "Elf"
#define CHARACTER_PACK_CLASS "Eldritch Knight"
#define CHARACTER_PACK_LEVEL 4
#define CHARACTER_PACK_MAX_HP 40
#define CHARACTER_PACK_AC 18
#define CHARACTER_PACK_SLOTS_MAX 3
#define CHARACTER_PACK_RESOURCE_NAME "Surge"
#define CHARACTER_PACK_RESOURCE_MAX 1

static const character_pack_entry_t CHARACTER_PACK_ACTIONS[] = {
    { "Longsword", "+6 hit | 1d8+4 slashing | 5 ft" },
    { "Handaxe", "+6 hit | 1d6+4 slashing | 20/60" },
    { "Second Wind", "Bonus action | regain 1d10+4 HP" },
};
#define CHARACTER_PACK_ACTIONS_COUNT 3

static const character_pack_entry_t CHARACTER_PACK_SPELLS[] = {
    { "Shield", "Reaction | self | +5 AC until next turn" },
    { "Magic Missile", "Action | 120 ft | three 1d4+1 darts" },
    { "Fire Bolt", "Action | 120 ft | +5 hit | 1d10 fire" },
};
#define CHARACTER_PACK_SPELLS_COUNT 3

static const character_pack_entry_t CHARACTER_PACK_CHECKS[] = {
    { "Athletics", "+6" },
    { "Perception", "+3" },
    { "Stealth", "+2" },
    { "Arcana", "+5" },
};
#define CHARACTER_PACK_CHECKS_COUNT 4

static const character_pack_entry_t CHARACTER_PACK_SHEET[] = {
    { "Defenses", "AC 18 | speed 30 | passive perception 13" },
    { "Saves", "STR +6 | CON +5 | WIS +1" },
    { "Equipment", "Longsword | shield | handaxes x2" },
    { "Features", "Action Surge | Second Wind | Weapon Bond" },
};
#define CHARACTER_PACK_SHEET_COUNT 4
